/*
 * MechInternalFrame.java
 *
 * Created on February 11, 2008, 9:46 PM
 */

package battletech;


import java.io.IOException;

/**
 *
 * @author  ryan
 */
public class MechInternalFrame extends javax.swing.JInternalFrame {
    
    /** Creates new form MechInternalFrame */
    public MechInternalFrame() throws IOException {
        initComponents();
    }
    
    public MechInternalFrame(String lanceName) throws IOException {
        initComponents();
        if(lanceName != null){
            mechPanel1.setLance(lanceName);
        }
    }
    
    public MechInternalFrame(String lanceName, String mechName, String tons) throws IOException {
        initComponents();
        if(lanceName != null){
            mechPanel1.setLance(lanceName);
        }
        if(mechName != null){
            mechPanel1.setMech(mechName);
        }
        if(tons != null){
            mechPanel1.setTons(tons);
        }
    }
    
    public MechPanel getMechPanel(){
        return mechPanel1;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() throws IOException {

        mechPanel1 = new MechPanel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setName("Form"); // NOI18N

        mechPanel1.setName("mechPanel1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mechPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mechPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private MechPanel mechPanel1;
    // End of variables declaration//GEN-END:variables
    
}
