# To change this template, choose Tools | Templates
# and open the template in the editor.

cancelButton.text=Cancel
okButton.text=OK
jLabel1.text=Lance:
lanceName.text=
jLabel2.text=Mech1:
jLabel3.text=Mech2:
jLabel4.text=Mech3:
jLabel6.text=Mech4:
jLabel5.text=Tons:
jLabel7.text=Tons:
jLabel8.text=Tons:
jLabel9.text=Tons:
tons1.text=
mech1.text=
mech2.text=
tons2.text=
mech3.text=
tons3.text=
mech4.text=
tons4.text=
