jLabel1.text=Dist:
jLabel6.text=Pilotskill:
jLabel5.text=Gunskill:
jLabel4.text=Tons:
jLabel3.text=Mech:
jLabel2.text=Lance:
showShotDlg.Action.shortDescription=
showShotDlg.Action.text=
jLabel13.text=Move:
#NOI18N
mechText.font=Tahoma-Bold-11
#NOI18N
lanceText.font=Tahoma-Bold-11
#NOI18N
shotsTable.font=Tahoma-Bold-11
jLabel7.text=Heat Mod:
jLabel11.text=Heat:
#NOI18N
jLabel11.font=Tahoma-Bold-11
standUpCheckBox.text=StandUp:
movedCheckBox.text=MOVED
firedCheckBox.text=FIRED
#NOI18N
firedCheckBox.font=Tahoma-Bold-11
#NOI18N
jCheckBox4.font=Tahoma-Bold-11
heatText.text=0
#NOI18N
heatText.font=Tahoma-Bold-11
addShotButton.text=+
deleteShotButton.text=-
jLabel9.text=EngineHits:
engineHitCheckBox1.text=
engineHitCheckBox2.text=
jLabel10.text=SensorHits:
sensorHitCheckBox1.text=
sensorHitCheckBox2.text=
#NOI18N
distanceSpinner.background=212,208,200
#NOI18N
distanceSpinner.foreground=212,208,200
#NOI18N
distanceSpinner.font=Tahoma-Plain-11
#NOI18N
shotsTable.selectionBackground=10, 36, 106
#NOI18N
shotsTable.selectionForeground=255, 255, 255
#NOI18N
shotsTable.foreground=0, 0, 0
#NOI18N
shotsTable.background=255, 255, 255
physCheckBox.text=PHYS
#NOI18N
physCheckBox.font=Tahoma 11 Bold
addPhysButton.text=+
deletePhysButton.text=-
#NOI18N
physTable.font=Tahoma 11 Bold
tonnageText.text=
weaponPanel.TabConstraints.tabTitle=Weapon
physicalPanel.TabConstraints.tabTitle=Physical
