stationaryRadio.text=Stationary
walkRadio.text=Walk
runRadio.text=Run
jumpRadio.text=Jump
chargeRadio.text=Charge
pounceRadio.text=Pounce
distanceText.text=0
jCheckBox1.text=Stand Up
jCheckBox2.text=Lie Down
jLabel1.text=Distance:
