# To change this template, choose Tools | Templates
# and open the template in the editor.

cancelButton.text=Cancel
okButton.text=OK
jLabel6.text=Attacks:
jLabel4.text=MOD:
#NOI18N
targetComboBox.font=Tahoma 11 Bold
jLabel2.text=Target:
jLabel5.text=Options:
#NOI18N
physOptionsList.font=Tahoma 11 Bold
#NOI18N
physAttacksList.font=Tahoma 11 Bold
