okButton.text=OK
cancelButton.text=Cancel
jLabel1.text=jLabel1
jLabel2.text=Target:
jLabel3.text=Range:
jLabel4.text=MOD:
jLabel5.text=Weapons:
jLabel6.text=Shots:
partialCoverCheckBox.text=Partial Cover
secondaryCheckBox.text=Secondary
#NOI18N
weaponsList.font=Tahoma-Bold-11
#NOI18N
shotsList.font=Tahoma-Bold-11
#NOI18N
targetComboBox.font=Tahoma-Bold-11
