jLabel1.text=Lance:
jLabel2.text=Mech:
jLabel3.text=Tonnage:
jLabel4.text=Gunskill:
jLabel5.text=Pilotskill:
uprightRadio.text=Upright
proneRadio.text=Prone
lanceText.text=
mechText.text=
tonnageText.text=
gunskillText.text=
pilotskillText.text=
